# Site settings
title: Donghao's blog
email: cinest8@gmail.com
url: https://github.com/D0nh4ll/freelancer-blog/
description: "no description"
keywords: "leng,dary "
skills: "Web Developer - English(if count) - Internet surfer"
meta_author: Donghao Chin
contact: "none"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames
social:
  - title: phone
    url: tel:+8613937702441
  - title: qq
    url: http://wpa.qq.com/msgrd?v=3&uin=2728713087&site=qq&menu=yes
  - title: weixin
    url: weixin://dl/business/?t=nowyou5eeme
  - title: bilibili
    url: https://space.bilibili.com/39448262

# Postal address (add as many lines as necessary)
address:
  - line: Beijing
  - line: Haidian,CUGB

# Credits content
credits: 'powered by Freelancer'

# Build settings
markdown: kramdown
permalink: /thoughts/:title/

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
